Repository chas-academy/u02-redesign-unit7, pull requests merged in 2020-10, with the labels that each got.

#9 Landing page + header/footer
  .gitignore
  assets/images/pages/index/corona_info.jpg
  components/footer.html
  components/header.html
  css/scss/_colors.scss
  css/scss/_forms-input-select.scss
  css/scss/_grid.scss
  css/scss/_lists.scss
  css/scss/_typography.scss
  css/scss/components/_button.scss
  css/scss/components/_footer.scss
  css/scss/components/_header.scss
  css/scss/pages/_index.scss
  css/style.min.css
  css/style.scss
  index.html
Labels: enhancement

#10 Publikationer
  assets/.DS_Store
  assets/png/publikationer_placeholder_thumb.png
  components/header.html
  pages/publikationer.html
Labels: enhancement

#12 Lagar regler tillsyn
  pages/lagar_regler_tillsyn.html
Labels: enhancement

#13 Anders
  assets/bilder/KK-start.png
  assets/bilder/Kontakttolk.png
  assets/bilder/SEQF.png
  assets/bilder/Scandinav_41YW_validering_webb.jpg
  assets/bilder/YH-start.png
  assets/images/verksamhetsomraden/ET-start.png
  assets/images/verksamhetsomraden/KK-start.png
  assets/images/verksamhetsomraden/Kontakttolk.png
  assets/images/verksamhetsomraden/SEQF.png
  assets/images/verksamhetsomraden/Scandinav_41YW_validering_webb.jpg
  assets/images/verksamhetsomraden/YH-start.png
  pages/verksamhetsomraden.html
Labels: enhancement

#22 Add interviews (UX)
  documentation/interview1-ulla.md
  documentation/interview2-adrian.md
Labels: enhancement

#27 Lagar regler tillsyn
  css/scss/pages/_lagar_regler_tillsyn.scss
  css/style.min.css
  css/style.scss
  pages/lagar_regler_tillsyn.html
Labels: enhancement

#23 Global overlay function
  assets/.DS_Store
  assets/misc/MYH-alt.ai
  assets/misc/MYH.ai
  assets/svg/logotype-alt.svg
  components/footer.html
  components/header.html
  css/scss/_colors.scss
  css/scss/_forms-input-select.scss
  css/scss/_lists.scss
  css/scss/_reset.scss
  css/scss/_typography.scss
  css/scss/components/_body-overlay.scss
  css/scss/components/_header.scss
  css/scss/components/_scroll-to-top.scss
  css/scss/components/_search.scss
  css/scss/pages/_index.scss
  css/style.min.css
  css/style.scss
  index.html
  js/body-overlay.js
  js/component-loader.js
  js/componentLoader.js
  js/menu-toggle.js
  js/scroll-to-top.js
  js/search.js
  pages/publikationer.html
Labels: enhancement

#30 Closes #24
  README.md
  css/README.md
Labels: documentation

#33 Parallax scroll
  css/scss/_parallax-scroll.scss
  css/scss/pages/_lagar-regler-tillsyn.scss
  css/style.min.css
  css/style.scss
  pages/lagar_regler_tillsyn.html
Labels: enhancement

#40 Create om oss
  css/scss/pages/_om-oss.scss
  css/style.scss
  pages/om-oss.html
Labels: backlog

#35 More formatting and style for publikationer-page
  css/scss/_colors.scss
  css/scss/_lists.scss
  css/scss/_typography.scss
  css/scss/pages/_publikationer.scss
  css/style.min.css
  pages/publikationer.html
Labels: update

#41 Closes #32 - Bugfix body overlay scrolllock
  components/footer.html
  components/header.html
  css/scss/_colors.scss
  css/scss/_grid.scss
  css/scss/_typography.scss
  css/scss/components/_body-overlay.scss
  css/scss/components/_footer.scss
  css/scss/components/_header.scss
  css/scss/pages/_index.scss
  css/scss/pages/_kontakt.scss
  css/style.min.css
  css/style.scss
  index.html
  js/body-overlay.js
  pages/kontakt.html
Labels: enhancement, update

#42 Merge Lagar regler tillsyn into main
  assets/images/bilder/paragraph-icon.png
  components/header.html
  css/scss/pages/_lagar-regler-tillsyn.scss
  css/scss/pages/_om-oss.scss
  pages/lagar_regler_tillsyn.html
  pages/om-oss.html
Labels: enhancement

#43 New statistik page
  assets/images/pages/statistik/statistics.jpg
  css/scss/pages/_publikationer.scss
  css/scss/pages/_statistik.scss
  css/style.min.css
  css/style.scss
  pages/Statistik.html
  pages/statistik.html
Labels: backlog

#45 Contact form contact page
  css/scss/_colors.scss
  css/scss/_forms-input-select.scss
  css/scss/_grid.scss
  css/scss/pages/_kontakt.scss
  css/style.min.css
  css/style.scss
  js/contact-form.js
  pages/kontakt.html
Labels: enhancement

#48 Bugfix contact form - Closes #47
  css/scss/_icons.scss
  css/scss/_lists.scss
  css/scss/components/_body-overlay.scss
  css/scss/components/_button.scss
  css/scss/pages/_kontakt.scss
  css/style.min.css
  css/style.scss
  js/body-overlay.js
  js/contact-form.js
  pages/kontakt.html
Labels: enhancement

#53 Fix links in menu to pages
  components/header.html
Labels: backlog

#50 Index page news
  assets/misc/MYH-alt.ai
  assets/misc/MYH.ai
  assets/svg/logotype-alt.svg
  assets/svg/logotype.svg
  components/header.html
  css/scss/_colors.scss
  css/scss/_parallax-scroll.scss
  css/scss/pages/_index.scss
  css/style.min.css
  index.html
  pages/kontakt.html
  pages/lagar-regler-tillsyn.html
  pages/nyheter.html
Labels: enhancement

#87 Closes #54
  components/header.html
  css/scss/components/_header.scss
  css/style.min.css
  js/menu-toggle.js
Labels: enhancement

#88 Closes issue #55
  css/scss/components/_body-overlay.scss
  css/style.min.css
Labels: enhancement

#89 Lagar regler tillsyn
  assets/images/bilder/penna.jpg
  css/scss/_typography.scss
  css/scss/pages/_lagar-regler-tillsyn.scss
  css/scss/pages/_om-oss.scss
  css/style.min.css
  pages/lagar-regler-tillsyn.html
  pages/om-oss.html
Labels: enhancement

#95 Lagar regler tillsyn
  css/scss/pages/_lagar-regler-tillsyn.scss
  css/scss/pages/_om-oss.scss
  css/style.min.css
  pages/lagar-regler-tillsyn.html
  pages/om-oss.html
Labels: enhancement

#97 Statistik fix
  css/scss/pages/_statistik.scss
  css/style.min.css
  pages/statistik.html
Labels: update

#98 Closes #62
  css/scss/pages/_kontakt.scss
  css/style.min.css
  pages/kontakt.html
Labels: enhancement

#99 Fix top section covid-19 info link (decided during group call)
  components/header.html
Labels: enhancement

#100 Fix search field width in mobile (wasn't 100%)
  css/scss/components/_header.scss
  css/style.min.css
Labels: enhancement

#102 Publikationer fix
  css/scss/pages/_publikationer.scss
  css/style.min.css
  pages/publikationer.html
Labels: update

#106 Publikationer layout mobile grid articles
  css/scss/pages/_publikationer.scss
  css/style.min.css
  css/style.scss
  pages/publikationer.html
Labels: update

#107 Closes #61
  css/scss/pages/_index.scss
  css/style.min.css
  index.html
Labels: update

#109 Close #58
  css/scss/_icons.scss
  css/scss/pages/_index.scss
  css/style.min.css
  index.html
Labels: update

#110 Update calendar on index to indicate next upcomming event with color diff
  css/scss/pages/_index.scss
  css/style.min.css
Labels: update

#112 Closes #59
  assets/images/pages/index/webopt-brooke-cagle--uHVRvDr7pg-unsplash.jpg
  assets/images/pages/index/wepopt-remi-walle-UOwvwZ9Dy6w-unsplash.jpg
  css/scss/_typography.scss
  css/scss/components/_button.scss
  css/scss/pages/_index.scss
  css/style.min.css
  index.html
Labels: update

#113 Closes #29 - Added breadcrumbs
  components/header.html
  css/scss/_icons.scss
  css/scss/components/_header.scss
  css/scss/pages/_index.scss
  css/style.min.css
  index.html
  js/component-loader.js
  js/menu-toggle.js
  pages/kontakt.html
  pages/lagar-regler-tillsyn.html
  pages/nyheter.html
  pages/om-oss.html
  pages/publikationer.html
  pages/statistik.html
  pages/verksamhetsomraden.html
Labels: enhancement, update

#115 Layout grid publikationer (tablet not working)
  css/scss/pages/_publikationer.scss
  css/style.min.css
  pages/publikationer.html
Labels: update

#117 Closes #101 - Initial parallax done
  assets/images/pages/index/webopt-green-chameleon-s9CC2SKySJM-unsplash.jpg
  css/scss/_parallax-scroll.scss
  css/scss/pages/_index.scss
  css/style.min.css
  index.html
Labels: enhancement, update

#118 Closes issue #114 - Add polyfill for smooth scroll on all browsers
  js/component-loader.js
  js/scroll-to-top.js
  js/smooth-scroll-polyfill.js
Labels: enhancement, update

#122 Publikationer close#96
  css/scss/pages/_publikationer.scss
  css/style.min.css
  pages/publikationer.html
Labels: update

#123 Lagar regler tillsyn
  css/scss/pages/_lagar-regler-tillsyn.scss
  css/scss/pages/_om-oss.scss
  css/style.min.css
  pages/lagar-regler-tillsyn.html
  pages/om-oss.html
Labels: enhancement

#125 Hash icons list
  css/scss/_icons.scss
  css/scss/_lists.scss
  css/style.min.css
  pages/publikationer.html
Labels: enhancement, update

#126 Rc 2020 10 30
  css/scss/pages/_om-oss.scss
  css/style.min.css
  pages/om-oss.html
Labels: enhancement

#127 Fix parallax for githib pages
  css/scss/_parallax-scroll.scss
  css/scss/pages/_index.scss
  css/style.min.css
  index.html
  js/component-loader.js
Labels: update

#128 Publikationer - layout, filter, pics
  assets/images/pages/publikationer/halsosjukvard.png
  assets/images/pages/publikationer/jamstalldutbildning.png
  assets/images/pages/publikationer/kvalitetskriterier.png
  assets/images/pages/publikationer/pedagogikanalys.png
  assets/images/pages/publikationer/sarskiltpedstod.png
  assets/images/pages/publikationer/sysselsattningsrapport.png
  css/scss/pages/_publikationer.scss
  css/scss/pages/_verksamhetsomraden.scss
  pages/publikationer.html
Labels: update

#129 Parallax Github pages backgroun fix
  css/scss/_parallax-scroll.scss
Labels: update

#130 Forgott collections declarations for parallax in github pages
  css/scss/_parallax-scroll.scss
Labels: update

#131 Update to index links and changed button styling + added date class
  css/scss/_dates.scss
  css/scss/components/_button.scss
  css/scss/pages/_index.scss
  css/style.min.css
  css/style.scss
  index.html
Labels: enhancement, update

#137 Accessibility - 'index' and 'kontakt'
  index.html
  pages/kontakt.html
Labels: backlog

#144 Laws rules regulations update
  css/style.min.css
Labels: update

#145 Update to lagar, regler och tillsyn
  css/scss/pages/_lagar-regler-tillsyn.scss
  css/style.min.css
  pages/lagar-regler-tillsyn.html
Labels: update
