Repository chas-academy/u02-redesign-unit7, pull requests merged in 2020-11, with the labels that each got.

#146 Index calendar fix
  css/scss/_parallax.scss
  css/scss/_reset.scss
  css/scss/_typography.scss
  css/scss/pages/_index.scss
  css/scss/pages/_statistik.scss
  css/style.min.css
  css/style.scss
  index.html
Labels: update

#147 Update text content
  pages/lagar-regler-tillsyn.html
Labels: enhancement

#148 Statistik parallax
  css/scss/pages/_statistik.scss
  css/style.min.css
  pages/publikationer.html
  pages/statistik.html
Labels: enhancement

#149 Accessibility statistik publikationer
  css/scss/pages/_publikationer.scss
  css/scss/pages/_statistik.scss
  css/style.min.css
  pages/publikationer.html
  pages/statistik.html
Labels: update

#150 Accessibility general
  index.html
  pages/om-oss.html
  pages/verksamhetsomraden.html
Labels: update

#151 Update scss to match html tag
  css/scss/pages/_om-oss.scss
  css/style.min.css
Labels: bug
